# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Daniadown Extensions"
client_id = "32e30ee6588b8fe015a87012463c1732"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false

[build]
dev_store_url = "partner-development-store.myshopify.com"
include_config_on_deploy = true
